Projected gui v2
ZdenekM/artable pull request #1
Opened 2016-12-07 11:31 UTC by jvida

2016-12-07 14:00 UTC, ZdenekM reviewed
- Součástí pull requestu by neměly být soubory: art_projected_gui/launch/app.launch a art_db/art.db.
- Chybí to hlavní: art_projected_gui/src/items/square_item.py (možná bych ještě zvážil přejmenování na square_grid_item.py), ať je z názvu jasnější o co jde. Zkuste "roscd art_projected_gui" a pak "git status ./" - uvidíte, které soubory nejsou přidané do gitu (untracked files). Ty pak přidáte takto "git add muj_novy_soubor.py".

2016-12-07 14:00 UTC, ZdenekM commented on art_projected_gui/launch/app.launch
> +        <!-- <rosparam param="projectors">["test"]</rosparam> -->
Tohle není žádný problém, ale kdyžtak pro příště dávejte pozor, abyste do commitu nepřidával soubory, kde jste si udělal změny pro svoji potřebu.

2016-12-07 14:00 UTC, ZdenekM commented on art_projected_gui/src/gui/ui_core.py
> +    # ! ja som pridal ! #
Odstraňte prosím nadbytečné komentáře.

2016-12-07 14:00 UTC, ZdenekM commented on art_projected_gui/src/gui/ui_core_ros.py
> +        self.program_vis.set_polygon(pts)   # ???
Tady byste spíš měl volat nějakou novou metodu ProgramItem - např. set_place_grid nebo tak něco. Zatím nemusí dělat nic, později bude updatovat odpovídající položku programu robota a ideálně by se asi mělo i zobrazovat uživateli, že už je grid nastavený.

2016-12-07 14:00 UTC, ZdenekM commented on art_projected_gui/src/gui/ui_core_ros.py
> +            self.add_square(translate("UICoreRos", "PICK SQUARE GRID"),  square_points,  square_changed=self.square_changed)
Nemá být ten grid spíš pro pokládání objektů - tedy "place"?

2016-12-07 14:00 UTC, ZdenekM commented on art_projected_gui/src/items/polygon_item.py
> +            self.pts.append(PolygonPointItem(scene,  rpm,  self.min[0],  self.min[1],  self))   # lavy horny roh
Tyto komentáře by klidně mohly zůstat, ale v angličtině prosím.

2016-12-07 15:54 UTC, jvida commented on art_projected_gui/src/gui/ui_core_ros.py
> +            self.add_square(translate("UICoreRos", "PICK SQUARE GRID"),  square_points,  square_changed=self.square_changed)
Ja som ho zatiaľ nahradil úplne za polygon, čiže sa mi zobrazí v ľavom rohu hneď jak sa vybere objekt, ktorý sa bude prenášať. To som sa chcel práve spýtať jak to bude prebiehať. Ako prvé sa zobrazí polygon okolo objektov, z ktorých sa bude presúvať a následne sa namiesto polygonu zobrazí ten môj grid?

2016-12-07 16:03 UTC, ZdenekM commented on art_projected_gui/src/gui/ui_core_ros.py
> +            self.add_square(translate("UICoreRos", "PICK SQUARE GRID"),  square_points,  square_changed=self.square_changed)
Aktuálně ten polygon slouží jen na vymezení oblasti, odkud se mají brát objekty jednoho typu (proto "pick polygon"). Robot (resp. art_brain) pak umí chycený objekt (art_brain vybere z vybraného polygonu jeden konkrétní objekt) zatím jen položit na zadané místo (place_pose). Grid tedy má být alternativou k místu pro položení. Zatím byste mohl místo nastavení místa pro položení (add_place v ui_core_ros.py) vždy nastavovat grid. Ideálně by pak měla být možnost toto zadat buď v programu robota (https://github.com/robofit/ar-table-common/blob/master/art_msgs/msg/ProgramItem.msg), nebo to nechat vybrat uživatele.

2016-12-07 16:07 UTC, jvida commented on art_projected_gui/src/gui/ui_core_ros.py
> +            self.add_square(translate("UICoreRos", "PICK SQUARE GRID"),  square_points,  square_changed=self.square_changed)
Jaj jasne, aj som tušil, že to má vlastne nahradiť place_pose. Ostatné veci som už upravil vďaka vášmu feedbacku, tak ešte zmením toto a commitnem to.

2016-12-08 00:54 UTC, jvida commented
Tak už by mal byť ten grid v poriadku dúfam. Cez deň skúsim ešte pridať k nemu text a nejak mu zmeniť farbu alebo mu aspoň nastaviť body na self.fixed = True, keď sa dokončí krok programu.

2016-12-09 07:50 UTC, ZdenekM requested changes
Ještě by bylo dobré se zamyslet nad tím, jak se to vlastně bude používat - aby použití bylo co nejjednodušší. Např. by ten grid asi měl být vždycky čtvercový (skládání objektů do krabice, na kraj stolu apod.). Jestli to chápu dobře, tak zatím máte rohy gridu, ale ještě by to chtělo zobrazovat objekty v něm - aby uživatel viděl kolik se jich tam vejde.

2016-12-09 07:50 UTC, ZdenekM commented on art_projected_gui/src/gui/ui_core.py
> -        self.remove_scene_items_by_type(SquareItem)     # JA SOM PRIDAL
Asi by tu měl být i ten SquareItem.

2016-12-09 07:50 UTC, ZdenekM commented on art_projected_gui/src/gui/ui_core_ros.py
> +                    self.add_place(translate("UICoreRos", "PLACE POSEi"),  x,  y,  self.place_pose_changed)
Proč to "i" na konci?

2016-12-09 07:50 UTC, ZdenekM commented on art_projected_gui/src/items/square_grid_item.py
> +        self.max = [0.75, 0.475]
Asi by bylo dobré grid na počátku "plácnout" doprostřed pracovního prostoru - ten ale není pevně daný. Např. u PlaceItem se počáteční pozice předává jako parametr, viz https://github.com/robofit/ar-table-itable/blob/master/art_projected_gui/src/gui/ui_core_ros.py#L344. Ideální by bylo dát ho doprostřed (ať si ho uživatel přesune kam chce) a podle vybraného typu objektu a velikosti gridu upravovat kolik objektů se do něj vejde (ke každému objektu známe jeho bounding box).

2017-05-16 13:04 UTC, closed without merging